### ISSUE TITLE
All Clients Register Row text

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#18]
The All Clients register row text is dependent on whether the client is a child U5 or a person older than 5 years.

<img width="379" alt="Picture2" src="https://user-images.githubusercontent.com/20777928/61237624-8820a900-a743-11e9-8f17-d8f7c31eb3b7.png">

If client is child U5, row text to display:
- [x] First line text: CG: {first_name} {middle_name} {surname} - This would be of the primary caregiver info for the family taken from the Registration information.
- [x] Second line text: {first_name} (middle_name} {surname}, {age} - This would be the child U5 information taken from Registration Info
- [x] Third line text: Child {sex} {fam_village} - Taken from the Registration Info.
- [x] Fourth line text (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Charity Otala as an example.

If client is a person over 5 years, row text to display:
- [x] First line text: {first_name} (middle_name} {surname}, {age} - Taken from the Registration Info.
- [x] Second line text: [Register type, if in register] {sex} {fam_village} - from Registration Info. Register type to display: ANC, PNC, Malaria, Family Planning
- [x] Third line text (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Charity Otala as an example.

**Comment by msschroeder** [comment]
QA Build Oct 18:
- Third line text (if the client has a referral): "Referral [number of days since referral is given] days ago" should appear (not the date of the referral) in both types of referrals
- Age should only be in years and months for children under 5 as in the CHW app

All shown below

![Screenshot_2019-10-23-10-14-45](https://user-images.githubusercontent.com/20777928/67371599-4fd00880-f585-11e9-88d2-fb67aef0a2d5.png)

**Comment by ellykits** [comment]
Referring to this quote:

> * Third line text (if the client has a referral): "Referral [number of days since referral is given] days ago" should appear (not the date of the referral) in both types of referrals

The date is only shown when the referral was done earlier than two days ago if I remember correctly or isn't that the desired behavior? https://github.com/OpenSRP/opensrp-client-chw/issues/562


![Screenshot_1571844401](https://user-images.githubusercontent.com/26865532/67409051-ad367a80-f5c2-11e9-8c4b-95e83912bb05.png)

**Comment by ellykits** [comment]
Issue on displaying month and days on adult's age is now fixed
![Screenshot_1571911577](https://user-images.githubusercontent.com/26865532/67475963-cb05ed00-f65f-11e9-8755-7c3787173655.png)

**Comment by msschroeder** [comment]
@ellykits It should use what is noted above: Referral [number of days since referral is given] days ago

**Comment by ellykits** [comment]
@msschroeder 
With regards to this comment mentioned above. Issue has been fixed now.
> It should use what is noted above: Referral [number of days since referral is given] days ago

![Screenshot_1573817566](https://user-images.githubusercontent.com/26865532/68940650-d3f86300-07b4-11ea-8e0d-af63d56b925e.png)

**Comment by msschroeder** [comment]
lgtm
