### ISSUE TITLE
Family planning referrals are not showing up on the HF app from CHW

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-hf#57]
- [ ] Family planning referrals are not showing up on the HF app from CHW

To replicate:
1. Open CHW app 
2. Open BA
3. Open FP 
4. Open a profile
5. Open FAB
6. Fill in Referral
7. Open HF app
8. It does not appear

**Comment by allan-on** [comment]
Did a referral from a profile as described and after syncing the referral showed as seen below
<img src="https://user-images.githubusercontent.com/16164649/78121494-1e047d00-7414-11ea-9fcf-734a5b660148.png" width="300" />

**Comment by msschroeder** [comment]
Lgtm
